# Generated by Django 3.0.5 on 2022-01-10 14:24

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(blank=True, validators=[api.validators.validate_score]),
        ),
    ]
